#!/bin/bash

apt-get install php5 -y

cp -Rf /vagrant/apache2/* /etc/apache2/
service apache2 restart

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
composer global require laravel/lumen-installer=~1.0
